name: Deploy version to production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter version (vX.X.X)'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Info
        run: echo "Getting everything for ${{ github.event.inputs.version }}"
        if: ${{ github.event.inputs.version }}

      # Checks-out ${{ github.event.inputs.version }} tag or latest commit from 'master' under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version }}
      
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Pacakge version
        run: echo "package.json version ${{ steps.package-version.outputs.current-version }}"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache node modules
        uses: actions/cache@v2
        id: node-modules
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install Dependencies
        # skip installing dependencies if cache is ok
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET_PROD }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION_PROD }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true

